# Generated by Django 4.1 on 2022-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerifyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('order_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nation', models.IntegerField(blank=True, null=True)),
                ('store', models.IntegerField(blank=True, null=True)),
                ('product_category', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('process_step', models.IntegerField(blank=True, default=0, null=True)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('order_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_a', models.CharField(blank=True, max_length=200, null=True)),
                ('name_b', models.CharField(blank=True, max_length=200, null=True)),
                ('name_c', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('counts', models.CharField(blank=True, max_length=200, null=True)),
                ('input_box', models.CharField(blank=True, max_length=200, null=True)),
                ('review_url', models.URLField(blank=True, null=True)),
                ('parts', models.CharField(blank=True, max_length=200, null=True)),
                ('process_step', models.IntegerField(default=0)),
                ('preview', models.URLField(blank=True, null=True)),
                ('finalview', models.URLField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nation_type_sel', to='setups.nationtype')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sel', to='setups.category')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type_sel', to='setups.producttype')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_type_sel', to='setups.storetype')),
                ('user_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mail_sel', to='users.userverifymodel')),
            ],
        ),
    ]
