# Generated by Django 4.1 on 2022-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='process_step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
