# Generated by Django 4.1 on 2022-10-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_process_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='input_box',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='review_url',
        ),
    ]
