# Generated by Django 4.1 on 2022-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion
import setups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_title', models.CharField(blank=True, max_length=200, null=True)),
                ('files', models.ImageField(blank=True, null=True, upload_to=setups.models.nationimage_path)),
                ('nation_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('nation_address', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_title', models.CharField(blank=True, max_length=200, null=True)),
                ('store_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('file_01', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('file_02', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('file_03', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('file_04', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('file_05', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('file_login', models.ImageField(blank=True, null=True, upload_to=setups.models.storeimage_path)),
                ('store_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('store_address', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verify', models.BooleanField(default=True)),
                ('phone_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('counts', models.CharField(blank=True, max_length=200, null=True)),
                ('input_box', models.CharField(blank=True, max_length=200, null=True)),
                ('description_index', models.CharField(blank=True, max_length=300, null=True)),
                ('content_text', models.CharField(blank=True, max_length=200, null=True)),
                ('guide_text', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('review_url', models.URLField(blank=True, null=True)),
                ('parts', models.CharField(blank=True, max_length=500, null=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='setups.category')),
            ],
        ),
    ]
