# Generated by Django 4.1 on 2022-10-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_no_create', models.BooleanField(default=False)),
                ('login_no_create', models.BooleanField(default=False)),
                ('url_popup', models.BooleanField(default=True)),
                ('login_popup', models.BooleanField(default=True)),
            ],
        ),
    ]
