# Generated by Django 4.1 on 2022-10-09 10:27

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, null=True, upload_to=content.models.file_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=content.models.thumb_file_path)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_product_type', to='setups.producttype')),
                ('user_mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to='users.userverifymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('option', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo_0', models.ManyToManyField(blank=True, related_name='item_01', to='content.filemodel')),
                ('photo_1', models.ManyToManyField(blank=True, related_name='item_02', to='content.filemodel')),
                ('photo_10', models.ManyToManyField(blank=True, related_name='item_11', to='content.filemodel')),
                ('photo_11', models.ManyToManyField(blank=True, related_name='item_12', to='content.filemodel')),
                ('photo_12', models.ManyToManyField(blank=True, related_name='item_13', to='content.filemodel')),
                ('photo_13', models.ManyToManyField(blank=True, related_name='item_14', to='content.filemodel')),
                ('photo_14', models.ManyToManyField(blank=True, related_name='item_15', to='content.filemodel')),
                ('photo_2', models.ManyToManyField(blank=True, related_name='item_03', to='content.filemodel')),
                ('photo_3', models.ManyToManyField(blank=True, related_name='item_04', to='content.filemodel')),
                ('photo_4', models.ManyToManyField(blank=True, related_name='item_05', to='content.filemodel')),
                ('photo_5', models.ManyToManyField(blank=True, related_name='item_06', to='content.filemodel')),
                ('photo_6', models.ManyToManyField(blank=True, related_name='item_07', to='content.filemodel')),
                ('photo_7', models.ManyToManyField(blank=True, related_name='item_08', to='content.filemodel')),
                ('photo_8', models.ManyToManyField(blank=True, related_name='item_09', to='content.filemodel')),
                ('photo_9', models.ManyToManyField(blank=True, related_name='item_10', to='content.filemodel')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type', to='setups.producttype')),
                ('user_mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to='users.userverifymodel')),
            ],
            options={
                'ordering': ['-created', '-user_mail'],
            },
        ),
    ]
