# Generated by Django 4.1 on 2022-10-14 06:14

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=content.models.file_path),
        ),
    ]
